// Translate the exercise catalogue's names with Claude, in batches, into frontend/src/names/<lang>.js
// Usage: ANTHROPIC_API_KEY=… node scripts/build-names.mjs es
import fs from 'node:fs'
const lang = process.argv[2] || 'es'
const LANG_NAME = { es: 'Spanish (Mexico)', fr: 'French', it: 'Italian', pt: 'Portuguese (Brazil)', de: 'German' }[lang] || lang
const mod = await import('../frontend/src/lib/exercises-data.js')
const d = mod.default || Object.values(mod)[0]
const all = (Array.isArray(d) ? d : Object.values(d)).map(e => ({ id: e.id, n: e.n, eq: e.eq, bp: e.bp, tg: e.tg }))
const out = fs.existsSync(`frontend/src/names/${lang}.json`) ? JSON.parse(fs.readFileSync(`frontend/src/names/${lang}.json`, 'utf8')) : {}
const todo = all.filter(e => !out[e.id])
console.log(all.length, 'exercises,', todo.length, 'to translate')
const key = process.env.ANTHROPIC_API_KEY
if (!key) { console.error('ANTHROPIC_API_KEY missing'); process.exit(1) }
const BATCH = 60
for (let i = 0; i < todo.length; i += BATCH) {
  const batch = todo.slice(i, i + BATCH)
  const body = {
    model: process.env.ANTHROPIC_MODEL || 'claude-haiku-4-5-20251001', max_tokens: 4000,
    system: `You translate gym exercise names into ${LANG_NAME} for a fitness app used by ordinary people, including older adults. Rules: use the name a Mexican gym-goer or trainer would actually say (e.g. "sentadilla", "peso muerto", "press de banca", "remo con barra", "curl de bíceps", "jalón al pecho", "elevaciones laterales", "zancadas", "plancha"); keep well-known loanwords when they are what people say ("press", "curl", "hip thrust", "burpees", "crunch"); be specific about equipment and variation but short (max ~6 words); never leave an English word that has a common Spanish equivalent; Title case first letter only; no trailing period.`,
    messages: [{ role: 'user', content: 'Translate each name. Return via the tool.\n' + batch.map(e => `${e.id} | ${e.n} | ${e.eq} | ${e.tg || e.bp}`).join('\n') }],
    tools: [{ name: 'names', description: 'translated names', input_schema: { type: 'object', properties: { items: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' } }, required: ['id', 'name'] } } }, required: ['items'] } }],
    tool_choice: { type: 'tool', name: 'names' }
  }
  const r = await fetch('https://api.anthropic.com/v1/messages', { method: 'POST', headers: { 'content-type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01' }, body: JSON.stringify(body) })
  const j = await r.json()
  const call = (j.content || []).find(b => b.type === 'tool_use')
  if (!call) { console.error('batch failed', i, JSON.stringify(j).slice(0, 200)); continue }
  for (const it of call.input.items) if (it.id && it.name && batch.some(e => e.id === it.id)) out[it.id] = String(it.name).trim().slice(0, 80)
  fs.writeFileSync(`frontend/src/names/${lang}.json`, JSON.stringify(out))
  console.log('done', Math.min(i + BATCH, todo.length), '/', todo.length)
}
const missing = all.filter(e => !out[e.id]).length
fs.writeFileSync(`frontend/src/names/${lang}.js`, '// generated by scripts/build-names.mjs — do not edit\nexport default ' + JSON.stringify(out) + '\n')
console.log('written', Object.keys(out).length, 'names;', missing, 'missing')
